@startuml sample1
!include skinparams.iuml

participant "Goroutine A" as A
queue "Channel" as C
participant "Goroutine B" as B

C <- B : Receive
activate C

A -> C : Send
activate C
A <<-- C
deactivate C

C -->> B
deactivate C

@enduml
