title: "Go のエラーハンドリング"
summary: |-
  私が Go のエラーハンドリングについて最初に記事にしたのは2015年のことだが，あれから Go も少しずつ変わってるし，私も当時よりは多少なりと理解が進んだと思うので，今まで書いた駄文を「全部入り」で本の形にしてみようと思う。

  主な内容：

  * エラー評価の基本
  * エラーの階層化
  * サードパーティのパッケージ
  * ぼくがかんがえたさいきょうのえらーろぐ
  * Panic と Recover

  寄付（サポート）大歓迎。ご笑覧のほどを。
topics: ["go", "programming", "error"]
published: false
price: 0 # 有料の場合200〜5000
toc_depth: 1
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - basics
  - evaluations
  - layered-error
  - third-party-errors
  - error-logging
  - panics
  - reference
  - colophon
